# ------------------------------------------------------------------------------
# Gramps Web - Full App
# ------------------------------------------------------------------------------
# Main Gramps Web container with Redis integration.
# Handles the web UI and queues background jobs for Celery.
# ------------------------------------------------------------------------------
services:
  grampsweb:
    container_name: grampsweb.${HOST_NAME}
    hostname: grampsweb.${HOST_NAME}.lan
    image: ghcr.io/gramps-project/grampsweb:latest           
    restart: unless-stopped
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
      DOMAINNAME: ${DOMAINNAME}
      HOST_NAME: grampsweb.${HOST_NAME}.lan
      GRAMPSWEB_TREE: "Gramps Web"
      GRAMPSWEB_CELERY_CONFIG__broker_url: "redis://grampsweb_redis:6379/0"
      GRAMPSWEB_CELERY_CONFIG__result_backend: "redis://grampsweb_redis:6379/0"
      GRAMPSWEB_RATELIMIT_STORAGE_URI: "redis://grampsweb_redis:6379/1"
    networks:
      - mediaserver
    ports:
      - "${GRAMPSWEB_PORT}:5000"
    volumes:
      - ${DOCKERDIR}/gramps/app/users:/app/users
      - ${DOCKERDIR}/gramps/app/gramps_index:/app/indexdir
      - ${DOCKERDIR}/gramps/app/thumbnail_cache:/app/thumbnail_cache
      - ${DOCKERDIR}/gramps/app/cache:/app/cache
      - ${DOCKERDIR}/gramps/app/secret:/app/secret
      - ${DOCKERDIR}/gramps/db:/root/.gramps/grampsdb
      - ${DOCKERDIR}/gramps/media:/app/media
      - ${DOCKERDIR}/gramps/tmp:/tmp
    depends_on:
      - grampsweb_redis
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "3"
    labels:
#      - "com.centurylinklabs.watchtower.enable=true"
      - "wud.managed=true"
      - "wud.trigger.update=true"