services:
  opentelemetry:
    container_name: opentelemetry.${HOST_NAME}
    hostname: opentelemetry.${HOST_NAME}.local
    image: otel/opentelemetry-collector-contrib:latest
    environment:
      TZ: ${TZ}
      PUID: ${PUID}
      PGID: ${PGID}
    networks:
      - mediaserver
    ports:
      - "4317:4317"  # OpenTelemetry gRPC receiver
      - "4318:4318"  # OpenTelemetry HTTP receiver
    volumes:
      - ${DOCKERDIR}/opentelemetry/otel-config.yaml:/otel-config.yaml
      - ${DOCKERDIR}/logs/opentelemetry:/var/log
    command:
      - "--config=/otel-config.yaml"
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    labels:
      ## Watchtower enabled?
      - "com.centurylinklabs.watchtower.enable=true"
