# Pi-hole - A network-wide ad blocker.

# Notes:
# This may need to change if you are running on windows or linux. Hence the commented variables etc
# Windows: Suggested, New-NetFirewallRule -DisplayName "Docker Desktop Backend" -Direction Inbound -Program "C:\program files\docker\docker\resources\com.docker.backend.exe" -Action Allow -Profile Private,Public
#

services:
  pihole:
    container_name: pihole.${HOST_NAME}
    hostname: pihole.${HOST_NAME}.local
    image: pihole/pihole:latest
 #   cap_add: #recommended for DHCP
 #     - NET_ADMIN
 #   dns:
 #     - 127.17.0.1
 #     - 1.1.1.1
 #     - 1.0.0.1
    network_mode: host
    environment:
      TZ: ${TZ}
      DNSMASQ_LISTENING: all
      FTLCONF_LOCAL_IPV4: ${PIHOLE_IP} # Windows set to host IP
      #FTLCONF_LOCAL_IPV4: ${PIHOLE_IP} # Linux set container IP
      VIRTUAL_HOST: pihole.${HOST_NAME}
      WEBPASSWORD_FILE: /run/secrets/pihole_password
      PIHOLE_DNS_1: ${PIHOLE_PRI} # Set to local if one server 127.17.0.1, if this is backup server set to primary
      PIHOLE_DOCKER_TAG: true
      #DHCP_ACTIVE: true
      #DHCP_START: 192.168.2.10
      #DHCP_END: 192.168.2.255
      #DHCP_ROUTER: 192.168.2.1
      TEMPERATUREUNIT: c
#    networks: #Use for linux
#      pihole_network:
#        ipv4_address: ${PIHOLE_IP}
 #   ports:
 #     - "53:53"
 #     - "53:53/udp"
 #     - "67:67/udp"
 #     - "80:80/tcp"
    volumes:
      - ${DOCKERDIR}/pihole:/etc/pihole
      - ${DOCKERDIR}/pihole/dnsmasq.d:/etc/dnsmasq.d
      - ${DOCKERDIR}/logs/pihole:/var/log
      - ${DOCKERDIR}/logs/pihole/lighttpd:/var/log/lighttpd
    restart: always
    secrets:
      - pihole_password
    labels:
      - "com.centurylinklabs.watchtower.enable=true"