# Radarr - Automatic movie download and management tool.
services:
  radarr:
    container_name: radarr.${HOST_NAME}
    hostname: radarr.${HOST_NAME}.local
    image: linuxserver/radarr:latest
    environment:
      TZ: ${TZ}
      PGID: ${PGID}
      PUID: ${PUID}
      DOMAINNAME: ${DOMAINNAME}
    networks:
      - mediaserver
    ports:
      - "${RADARR_PORT}:7878"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DOCKERDIR}/radarr/config:/config
      - ${USERDOWNLOAD}/Torrents:/downloads
      - ${MEDIASHARE}:/media
      - ${DOCKERDIR}/logs/radarr:/var/log
    restart: always
    security_opt:
       - no-new-privileges:true
      # labels:
      #   - "traefik.enable=true"            
      #   ## HTTP Routers
      #   - "traefik.http.routers.radarr-rtr.entrypoints=https"
      #   - "traefik.http.routers.radarr-rtr.rule=Host(`radarr.${DOMAINNAME}`)"      
      #   - "traefik.http.routers.radarr-rtr.middlewares=chain-oauth@file"
      #   - "traefik.http.routers.radarr-rtr.tls.options=tls-opts@file"
      #   ## Docker Network
      #   - "traefik.docker.network=mediaserver"
      #   ## HTTP Services
      #   - "traefik.http.routers.radarr-rtr.service=radarr-svc"      
      #   - "traefik.http.services.radarr-svc.loadbalancer.server.port=7878"
      #   ## Watchtower Enable
      #   - "com.centurylinklabs.watchtower.enable=true"
      #   ## Homepage Labels
      #   - "homepage.group=Media"
      #   - "homepage.name=Radarr"
      #   - "homepage.icon=radarr.png"
      #   - "homepage.href=http://radarr.${DOMAINNAME}/"
      #   - "homepage.description=Movie download manager"
      #   ## Homepage Widget
      #   - "homepage.widget.type=radarr"
      #   - "homepage.widget.url=http://radarr.${HOST_NAME}:7878"
      #   - "homepage.widget.key=${RADARR_API_KEY}"
