## look at https://www.smarthomebeginner.com/cloudflare-settings-for-traefik-docker/ setup proxy on *.${DOMAINNAME} to protect everything behind dns

services:
  traefik-cloudflare-companion:
    container_name: traefik-cloudflare-companion.${HOST_NAME}
    hostname: traefik-cloudflare-companion.${HOST_NAME}.local
    image: tiredofit/traefik-cloudflare-companion
    environment:
      TZ: ${TZ}
      PUID: ${PUID}
      PGID: ${PGID}
      TRAEFIK_VERSION: 2
      CF_EMAIL_FILE: /run/secrets/cf_email
      CF_TOKEN_FILE: /run/secrets/cf_token
      TARGET_DOMAIN: ${DOMAINNAME}
      DOMAIN1: ${DOMAINNAME}
      DOMAIN1_ZONE_ID_FILE: /run/secrets/cf_zone_id # Copy from Cloudflare Overview page
      DOMAIN1_PROXIED: TRUE
    networks:
      - mediaserver
    volumes:
      # Uncomment if needed
      # - /var/run/docker.sock:/var/run/docker.sock
      - ${DOCKERDIR}/traefik-cloudflare-companion/config:/config
      - ${DOCKERDIR}/logs/traefik-cloudflare-companion:/var/log
    restart: always
    security_opt:
      - no-new-privileges:true
    secrets:
      - cf_token
      - cf_email
      - cf_zone_id
    labels:
      # Add hosts specified in rules here to force cf-companion to create the CNAMEs
      # Since cf-companion creates CNAMEs based on host rules, this a workaround for non-docker/external apps
      - "traefik.http.routers.cf-companion-rtr.rule=HostHeader(`pihole.${DOMAINNAME}`) || HostHeader(`printer.${DOMAINNAME}`)"
      ## Watchtower enabled?
      - "com.centurylinklabs.watchtower.enable=true"
