# Traefik - A modern reverse proxy and load balancer.
services:
  traefik:
    container_name: traefik.${HOST_NAME}
    hostname: traefik.${HOST_NAME}.local
    image: traefik:2.10
    command:
      - --global.checkNewVersion=true
      - --global.sendAnonymousUsage=true
      - --entryPoints.http.address=:80
      - --entryPoints.https.address=:443
      - --entrypoints.https.forwardedHeaders.trustedIPs=${CLOUDFLARE_IPS},${LOCAL_NETWORK}
      - --entryPoints.traefik.address=:8080
      - --api=true
      - --api.dashboard=true
      - --log=true
      - --log.filePath=/logs/traefik.log
      - --log.level=DEBUG
      - --accessLog=true
      - --accessLog.filePath=/logs/access.log
      - --accessLog.bufferingSize=100
      - --accessLog.filters.statusCodes=204-299,400-499,500-599
      - --providers.docker=true
      - --providers.docker.endpoint=unix:///var/run/docker.sock
      - --providers.docker.exposedByDefault=false
      - --entrypoints.https.http.tls.options=tls-opts@file
      - --entrypoints.https.http.tls.certresolver=dns-cloudflare
      - --entrypoints.https.http.tls.domains[0].main=${DOMAINNAME}
      - --entrypoints.https.http.tls.domains[0].sans=*.$DOMAINNAME
      - --providers.docker.network=mediaserver
      - --providers.docker.swarmMode=false
      - --providers.file.directory=/rules
      - --providers.file.watch=true
      - --certificatesResolvers.dns-cloudflare.acme.email=${CLOUDFLARE_EMAIL}
      - --certificatesResolvers.dns-cloudflare.acme.storage=/acme.json
      - --certificatesResolvers.dns-cloudflare.acme.dnsChallenge.provider=cloudflare
      - --certificatesResolvers.dns-cloudflare.acme.dnsChallenge.resolvers=1.1.1.1:53,1.0.0.1:53
      - --certificatesResolvers.dns-cloudflare.acme.dnsChallenge.delayBeforeCheck=90
    environment:
      TZ: ${TZ}
      DOMAIN: ${DOMAINNAME}
      HTPASSWD_FILE: /run/secrets/htpasswd
      CF_DNS_API_TOKEN_FILE: /run/secrets/cf_dns_api_token
      CF_EMAIL_FILE: /run/secrets/cf_email
      DOMAINNAME: ${DOMAINNAME}
      LOG_LEVEL: WARN
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - mediaserver
    ports:
      - mode: host
        protocol: tcp
        published: 80
        target: 80
      - mode: host
        protocol: tcp
        published: 443
        target: 443
    restart: always
    secrets:
      - cf_email
      - cf_api_key
      - cf_dns_api_token
      - htpasswd
    security_opt:
      - no-new-privileges:true
    volumes:
      - ${DOCKERDIR}/traefik2/config:/config
      - ${DOCKERDIR}/traefik2/rules:/rules
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${DOCKERDIR}/traefik2/acme.json:/acme.json
      - ${DOCKERDIR}/logs/traefik:/var/log
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.http-catchall.entrypoints=http"
      - "traefik.http.routers.http-catchall.rule=HostRegexp(`{host:.+}`)"
      - "traefik.http.routers.http-catchall.middlewares=redirect-to-https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.routers.traefik-rtr.entrypoints=https"
      - "traefik.http.routers.traefik-rtr.rule=Host(`traefik.${DOMAINNAME}`)"
      - "traefik.http.routers.traefik-rtr.tls=true"
      ## Middlewares
      - "traefik.http.routers.traefik-rtr.middlewares=chain-oauth@file,middlewares-rate-limit@file,middlewares-secure-headers@file"
      ## Docker Network
      - "traefik.docker.network=mediaserver"
      ## HTTP Services
      - "traefik.http.routers.traefik-rtr.service=api@internal"
      ## Watchtower Enable
      - "com.centurylinklabs.watchtower.enable=false"

