# Bazarr - Subtitle management for your media files.
services:
  bazarr:
    container_name: bazarr.${HOST_NAME}
    hostname: bazarr.${HOST_NAME}.local
    image: lscr.io/linuxserver/bazarr:latest
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
      DOMAINNAME: ${DOMAINNAME}      
      HOST_NAME: ${HOST_NAME}
      BAZARR_API_KEY: ${BAZARR_API_KEY}      
    networks:
      - mediaserver
    ports:
      - "${BAZARR_PORT}:6767"
    volumes:
      - ${DOCKERDIR}/bazarr/config:/config
      - ${MEDIASHARE}:/media
      - ${DOCKERDIR}/logs/bazarr:/var/log
    restart: always
    security_opt:
      - no-new-privileges:true   
    labels:
      ## Watchtower Enable
      - "com.centurylinklabs.watchtower.enable=true"
      ## Homepage Labels
      - "homepage.group=Media"
      - "homepage.name=Bazarr"
      - "homepage.icon=bazarr.png"
      - "homepage.href=http://bazarr.${DOMAINNAME}/"
      - "homepage.description=Subtitle management"
      ## Homepage Widget
      - "homepage.widget.type=bazarr"
      - "homepage.widget.url=http://bazarr.${HOST_NAME}:6767"
      - "homepage.widget.key=${BAZARR_API_KEY}"
