# Bazarr - Subtitle management for your media files.
services:
  bazarr:
    container_name: bazarr.${HOST_NAME}
    hostname: bazarr.${HOST_NAME}.local
    image: lscr.io/linuxserver/bazarr:latest
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
      DOMAINNAME: ${DOMAINNAME}
    networks:
      - mediaserver
    ports:
      - "${BAZARR_PORT}:6767"
    volumes:
      - ${DOCKERDIR}/bazarr/config:/config
      - ${MEDIASHARE}:/media
      - ${DOCKERDIR}/logs/bazarr:/var/log
    restart: always
    security_opt:
      - no-new-privileges:true   
    labels:
      - "traefik.enable=true"      
      ## HTTP Routers
      - "traefik.http.routers.bazarr-rtr.entrypoints=https"
      - "traefik.http.routers.bazarr-rtr.rule=Host(`bazarr.${DOMAINNAME}`)"      
      - "traefik.http.routers.bazarr-rtr.middlewares=chain-oauth@file"
      - "traefik.http.routers.bazarr-rtr.tls.options=tls-opts@file"
      ## Docker Network
      - "traefik.docker.network=mediaserver"
      ## HTTP Services
      - "traefik.http.routers.bazarr-rtr.service=bazarr-svc"      
      - "traefik.http.services.bazarr-svc.loadbalancer.server.port=6767"
      ## Watchtower Enable
      - "com.centurylinklabs.watchtower.enable=true"
      ## Homepage Labels
      - "homepage.group=Media"
      - "homepage.name=Bazarr"
      - "homepage.icon=bazarr.png"
      - "homepage.href=http://bazarr.${DOMAINNAME}/"
      - "homepage.description=Subtitle management"
      ## Homepage Widget
      - "homepage.widget.type=bazarr"
      - "homepage.widget.url=http://bazarr.${HOST_NAME}:6767"
      - "homepage.widget.key=${BAZARR_API_KEY}"
