# Calibre-web - A web-based e-book management system.
# Default Username: admin
# Default Password: admin123
# Please change these

services:
  calibre-web:
    container_name: calibre-web.${HOST_NAME}
    hostname: calibre-web.${HOST_NAME}.lan
    image: linuxserver/calibre-web:latest
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
      HOST_NAME: ${HOST_NAME}.lan
      DOMAINNAME: ${DOMAINNAME}
      DOCKER_MODS: linuxserver/mods:universal-calibre
    networks:
      - mediaserver
    ports:
      - "${CALIBRE_WEB_PORT}:8083"
    volumes:
      - ${DOCKERDIR}/calibre-web/config:/config
      - ${MEDIASHARE}/Books:/database # Calibre database directory
      - ${MEDIASHARE}/Books:/books # Calibre library directory
      - ${USERDOWNLOAD}/Torrents:/downloads
      - ${DOCKERDIR}/logs/calibre-web:/var/log
    restart: always
    security_opt:
      - no-new-privileges:true
    labels:
      ## Watchtower enabled?
      - "com.centurylinklabs.watchtower.enable=true"
      ## Homepage Labels
      - "homepage.group=Media"
      - "homepage.name=Calibre-Web"
      - "homepage.icon=calibre-web.png"
      - "homepage.href=https://calibre-web.${DOMAINNAME}/"
      - "homepage.description=Browser-based eBook library"
      ## Homepage Widget
      - "homepage.widget.type=calibreweb"
      - "homepage.widget.url=http://calibre-web.${HOST_NAME}:8083"
      - "homepage.widget.username=${CALIBRE_WEB_USER}"
      - "homepage.widget.password=${CALIBRE_WEB_PASS}"
