# Calibre - An e-book management software.
# Windows: Getting error on x11 look later

services:
  calibre:
    container_name: calibre.${HOST_NAME}
    hostname: calibre.${HOST_NAME}.local
    image: ghcr.io/linuxserver/calibre:latest
    environment:
      TZ: ${TZ}
      PUID: ${PUID}
      PGID: ${PGID}
      DOMAINNAME: ${DOMAINNAME}
      UMASK: 2
    networks:
      - mediaserver
    ports:
      - "${CALIBRE_PORT}:8080"
      - "${CALIBRE_PORT2}:8081"
      - "${CALIBRE_PORT3}:8181"
    volumes:
      - ${DOCKERDIR}/calibre/config:/config
      - ${DOCKERDIR}/calibre/uploads:/uploads
      - ${DOCKERDIR}/calibre/plugins:/plugins
      - ${MEDIASHARE}/Books:/books
      - ${USERDOWNLOAD}/Torrents:/downloads
      - ${DOCKERDIR}/logs/calibre:/var/log
      - ${DOCKERDIR}/logs/calibre/nginx:/var/log/nginx
    restart: always
    security_opt:
      - no-new-privileges:true
    labels:
      ## Watchtower enabled?
      - "com.centurylinklabs.watchtower.enable=true"
      ## Homepage Labels
      - "homepage.group=Media"
      - "homepage.name=Calibre"
      - "homepage.icon=calibre.png"
      - "homepage.href=https://calibre.${DOMAINNAME}/"
      - "homepage.description=E-book management and conversion"