# Dozzle - A lightweight log viewer for Docker containers.
services:
  dozzle:
    container_name: dozzle.${HOST_NAME}
    hostname: dozzle.${HOST_NAME}.local
    image: amir20/dozzle:latest
    environment:
      DOMAINNAME: ${DOMAINNAME}
      DOZZLE_FILTER: status=running
      DOZZLE_LEVEL: info
    networks:
      - mediaserver
    ports:
      - "${DOZZLE_PORT}:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # Container access to the Docker API, enabling it to manage other containers on the same host
      - ${DOCKERDIR}/dozzle/config:/config
      - ${DOCKERDIR}/logs/dozzle:/var/log
    restart: always
    security_opt:
      - no-new-privileges:true
    labels:
      ## Watchtower enabled?
      - "com.centurylinklabs.watchtower.enable=true"
      ## Homepage Labels
      - "homepage.group=Infrastructure"
      - "homepage.name=Dozzle"
      - "homepage.icon=dozzle.png"
      - "homepage.href=https://dozzle.${DOMAINNAME}/"
      - "homepage.description=Stream container logs in real-time"
