# ErsatzTV - A pseudo-live channel server.
# jasongdove/ersatztv-vaapi for AMD GPUs and Intel CPUs with QuickSync
# use jasongdove/ersatztv for software transcoding
# or jasongdove/ersatztv-nvidia for Nvidia transcoding

services:
  ersatztv:
    container_name: ersatztv.${HOST_NAME}
    hostname: ersatztv.${HOST_NAME}.local
    image: jasongdove/ersatztv:develop-vaapi
    devices:
      #- /dev/dri:/dev/dri
      - /dev/dri/renderD128:/dev/dri/renderD128
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
      DOMAINNAME: ${DOMAINNAME}
    networks:
      - mediaserver
    ports:
      - "${ERSATZTV_PORT}:8409"
    volumes:
      - ${DOCKERDIR}/ersatztv:/root/.local/share/ersatztv
      - ${MEDIASHARE}/Videos:/media:ro
      - ${DOCKERDIR}/ersatztv/config:/config
      - ${DOCKERDIR}/logs/ersatztv:/var/log
    restart: always
    security_opt:
      - no-new-privileges:true
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    ## Homepage Labels
      - "homepage.group=Media"
      - "homepage.name=ErsatzTV"
      - "homepage.icon=tv"
      - "homepage.href=https://ersatztv.${DOMAINNAME}/"
      - "homepage.description=Virtual live TV channels from your media library"
