# ------------------------------------------------------------------------------ 
# Frigate - NVR with AI Object Detection
# ------------------------------------------------------------------------------ 
# Provides real-time object detection, recording, and MQTT events for HA.
# Uses RTSP streams from Lorex DVR, publishes detections via MQTT.
# ------------------------------------------------------------------------------ 

services:
  frigate:
    container_name: frigate.${HOST_NAME}
    hostname: frigate.${HOST_NAME}.lan
    image: ghcr.io/blakeblackshear/frigate:stable
    devices:
      - /dev/dri:/dev/dri
    privileged: true
    shm_size: "512m"   # Shared memory for ffmpeg
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
      DOMAINNAME: ${DOMAINNAME}
      HOST_NAME: ${HOST_NAME}.lan
    networks:
      - mediaserver
    ports:
      - "${FRIGATE_WEB_PORT}:5000"
      - "${FRIGATE_RTMP_PORT}:1935"
    volumes:
      - ${DOCKERDIR}/frigate/config:/config
      - ${DOCKERDIR}/frigate/media:/media/frigate
      - /etc/localtime:/etc/localtime:ro
    #  - /dev/bus/usb:/dev/bus/usb   # Only if you add a Coral USB
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - "homepage.group=Infrastructure"
      - "homepage.name=Frigate"
      - "homepage.icon=camera.png"
      - "homepage.href=https://frigate.${DOMAINNAME}/"
      - "homepage.description=AI-powered NVR and object detection"