# Heimdall Internal - A separate Heimdall instance.
services:
  heimdallint:
    container_name: heimdallint.${HOST_NAME}
    hostname: heimdallint.${HOST_NAME}.local
    image: linuxserver/heimdall:latest
    environment:
      TZ: ${TZ}
      PUID: ${PUID}
      PGID: '100' #can't be an admin group.
      DOMAINNAME: ${DOMAINNAME}
    networks:
      - mediaserver
    ports:
      - "${HEIMDALLINT_PORT}:80"
    volumes:
      - ${DOCKERDIR}/heimdallint/config:/config
      - ${DOCKERDIR}/logs/heimdallint:/var/log
      - ${DOCKERDIR}/logs/heimdallint/nginx:/var/log/nginx
    restart: always
    security_opt:
      - no-new-privileges:true
    labels:
      ## Watchtower enabled?
      - "com.centurylinklabs.watchtower.enable=true"
