services:
  libation:
    container_name: libation.${HOST_NAME}
    hostname: libation.${HOST_NAME}.local
    image:  ghcr.io/bcnelson/libation_docker:latest
    user: "1000:100"
    environment:
      TZ: ${TZ}
      PUID: ${PUID}
      PGID: ${PGID}
      LIBATION_CREATE_DB: true
      SLEEP_TIME: 1440m
    networks:
      - mediaserver
    ports:
      - ${LIBATION_PORT}:3000  # Replace SERVICE_PORT with the actual port you want to expose. Add SERVICE_PORT to your .env file.
    volumes:
      # Uncomment if needed
      # - /var/run/docker.sock:/var/run/docker.sock
      - ${DOCKERDIR}/libation/config:/config
      - ${DOCKERDIR}/logs/libation:/var/log
      - ${MEDIASHARE}/Books/audiobooks:/data
    restart: always
    security_opt:
      - no-new-privileges:true
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.libation-rtr.entrypoints=https"
      ## Middlewares
      - "traefik.http.routers.libation-rtr.rule=Host(libation${HOST_SUFFIX}.${DOMAINNAME})"
      - "traefik.http.routers.libation-rtr.middlewares=chain-oauth@file"
      ## Docker Network
      - "traefik.docker.network=mediaserver"
      ## HTTP Services
      - "traefik.http.routers.libation-rtr.service=libation-svc"
      - "traefik.http.services.libation-svc.loadbalancer.server.port=3000" # Replace with the internal port of the service
      ## Watchtower enabled?
      - "com.centurylinklabs.watchtower.enable=true"
      ## Homepage Labels
      - "homepage.group=Media"
      - "homepage.name=libation"
      - "homepage.icon=libation.png"
      - "homepage.href=http://libation.${DOMAINNAME}/"
      - "homepage.description=Audible audiobook manager"
      ## Homepage Widget
      - "homepage.widget.type=Other"
      - "homepage.widget.url=http://libation.${HOST_NAME}:3000" # Replace with the internal port of the service
      - "homepage.widget.key=${libation_API_KEY}"