services:
  lidify:
    container_name: lidify.${HOST_NAME}
    hostname: lidify.${HOST_NAME}.local
    image: thewicklowwolf/lidify:latest
    environment:
      TZ: ${TZ}
      PUID: ${PUID}
      PGID: ${PGID}
      DOMAINNAME: ${DOMAINNAME}
      APP_NAME: Lidify
      lidarr_address: http://localhost:8686 # Change this if Lidarr is not on the same server
      LIDARR_API_KEY_FILE: /secrets/lidarr_api_key
      ROOT_FOLDER_PATH: ${MEDIASHARE}/Music # Should match the root folder for music in Lidarr
      MODE: Spotify
      SPOTIFY_CLIENT_ID_FILE: /secrets/spotify_client_id
      SPOTIFY_CLIENT_SECRET_FILE: /secrets/spotify_client_secret
    networks:
      - mediaserver
    ports:
      - ${LIDIFY_PORT}:5000
    volumes:
      - ${DOCKERDIR}/lidify/config:/lidify/config
      - ${DOCKERDIR}/logs/lidify:/var/log
    restart: always
    security_opt:
      - no-new-privileges:true
    secrets:
      - lidarr_api_key
      - spotify_client_id
      - spotify_client_secret
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.lidify-rtr.entrypoints=https"
      ## Middlewares
      - "traefik.http.routers.lidify-rtr.rule=Host(lidify${HOST_SUFFIX}.${DOMAINNAME})"
      - "traefik.http.routers.lidify-rtr.middlewares=chain-oauth@file"
      ## Docker Network
      - "traefik.docker.network=mediaserver"
      ## HTTP Services
      - "traefik.http.routers.lidify-rtr.service=lidify-svc"
      - "traefik.http.services.lidify-svc.loadbalancer.server.port=5000"
      ## Watchtower enabled?
      - "com.centurylinklabs.watchtower.enable=true"
