# MineOS - A web-based Minecraft server management tool.

services:
  mineos:
    container_name: mineos.${HOST_NAME}
    hostname: mineos.${HOST_NAME}.local
    image: hexparrot/mineos:latest
    environment:
      TZ: ${TZ}
      PUID: ${PUID}
      PGID: ${PGID}
      DOMAINNAME: ${DOMAINNAME}
      USER_PASSWORD_FILE: /run/secrets/mineos_password
    networks:
      - mediaserver
    ports:
      - "${MINEOS_PORT}:8443"
      - "25565-25577:25565-25577" #Ports for Game(s)
    volumes:
      - ${DOCKERDIR}/mineos/config:/config
      - ${DOCKERDIR}/logs/mineos:/var/log
      - ${DOCKERDIR}/mineos/var/games/minecraft:/var/games/minecraft
      - ${DOCKERDIR}/logs/mineos/supervisor:/var/log/supervisor
    restart: unless-stopped
    secrets:
      - mineos_password
    security_opt:
      - no-new-privileges:true
    labels:
       ## Watchtower enabled?cd      
      - "com.centurylinklabs.watchtower.enable=true"
      ## Homepage Labels
      - "homepage.group=Infrastructure"
      - "homepage.name=MineOS"
      - "homepage.icon=minecraft"
      - "homepage.href=https://mineos.${DOMAINNAME}/"
      - "homepage.description=Manage Minecraft servers via web UI"    