# MineOS - A web-based Minecraft server management tool.

services:
  mineos:
    container_name: mineos.${HOST_NAME}
    hostname: mineos.${HOST_NAME}.local
    image: hexparrot/mineos:latest
    environment:
      TZ: ${TZ}
      PUID: ${PUID}
      PGID: ${PGID}
      DOMAINNAME: ${DOMAINNAME}
      USER_PASSWORD_FILE: /run/secrets/mineos_password
    networks:
      - mediaserver
    ports:
      - "${MINEOS_PORT}:8443"
      - "25565-25577:25565-25577" #Ports for Game(s)
    volumes:
      - ${DOCKERDIR}/mineos/config:/config
      - ${DOCKERDIR}/logs/mineos:/var/log
      - ${DOCKERDIR}/mineos/var/games/minecraft:/var/games/minecraft
      - ${DOCKERDIR}/logs/mineos/supervisor:/var/log/supervisor
    restart: unless-stopped
    secrets:
      - mineos_password
    security_opt:
      - no-new-privileges:true
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.mineos-rtr.entrypoints=https"
      - "traefik.http.routers.mineos-rtr.rule=Host(`mineos.${DOMAINNAME}`)"
      - "traefik.http.routers.mineos-rtr.tls=true"
      ## Middlewares
      - "traefik.http.routers.mineos-rtr.middlewares=chain-oauth@file"
      - "traefik.http.middlewares.add-mineos.addPrefix.prefix=/admin"
      ## Docker Network
      - "traefik.docker.network=mediaserver"
      ## HTTP Services
      - "traefik.http.routers.mineos-rtr.service=mineos-svc"      
      - "traefik.http.services.mineos-svc.loadbalancer.server.port=8443"
       ## Watchtower enabled?cd      
      - "com.centurylinklabs.watchtower.enable=true"