services:
  musicbrainz:
    container_name: musicbrainz.${HOST_NAME}
    hostname: musicbrainz.${HOST_NAME}.local
    image: linuxserver/musicbrainz:latest
    environment:
      TZ: ${TZ}
      PUID: ${PUID}
      PGID: ${PGID}
      DOMAINNAME: ${DOMAINNAME}
    networks:
      - mediaserver
    ports:
      - ${MUSICBRAINZ_PORT}:80
    volumes:
      - ${DOCKERDIR}/musicbrainz/config:/config
      - ${DOCKERDIR}/logs/musicbrainz:/var/lib/nginx/logs
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    labels:
      ## Watchtower enabled?
      - "com.centurylinklabs.watchtower.enable=true"
      ## Homepage Labels
      - "homepage.group=Media"
      - "homepage.name=MusicBrainz"
      - "homepage.icon=music"
      - "homepage.href=https://musicbrainz.${DOMAINNAME}/"
      - "homepage.description=Open music metadata server"
