services:
  musicbrainz:
    container_name: musicbrainz.${HOST_NAME}
    hostname: musicbrainz.${HOST_NAME}.local
    image: linuxserver/musicbrainz:latest
    environment:
      TZ: ${TZ}
      PUID: ${PUID}
      PGID: ${PGID}
      DOMAINNAME: ${DOMAINNAME}
    networks:
      - mediaserver
    ports:
      - ${MUSICBRAINZ_PORT}:80
    volumes:
      - ${DOCKERDIR}/musicbrainz/config:/config
      - ${DOCKERDIR}/logs/musicbrainz:/var/log
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.musicbrainz-rtr.entrypoints=https"
      ## Middlewares
      - "traefik.http.routers.musicbrainz-rtr.rule=Host(musicbrainz${HOST_SUFFIX}.${DOMAINNAME})"
      - "traefik.http.routers.musicbrainz-rtr.middlewares=chain-oauth@file"
      ## Docker Network
      - "traefik.docker.network=mediaserver"
      ## HTTP Services
      - "traefik.http.routers.musicbrainz-rtr.service=musicbrainz-svc"
      - "traefik.http.services.musicbrainz-svc.loadbalancer.server.port=80"
      ## Watchtower enabled?
      - "com.centurylinklabs.watchtower.enable=true"
