# Nextcloud - An open-source cloud storage solution.

# *************************** VOLUMES ******************************************
# This volume is required to make nextcloud_aio_mastercontainer work
volumes:
  nextcloud_aio_mastercontainer:
    name: nextcloud_aio_mastercontainer # This line is not allowed to be changed

services:
  nextcloud:
    container_name: nextcloud-aio-mastercontainer # cannot use .${HOST_NAME} nextcloud-aio very picky on naming
    hostname: nextcloud.${HOST_NAME}.local
    image: nextcloud/all-in-one:latest
    environment:
      APACHE_PORT: 11000
      APACHE_IP_BINDING: ${SERVER_IP}
      NEXTCLOUD_DATADIR: /homes
      NEXTCLOUD_MOUNT: /exstorage # Allows the Nextcloud container to access the chosen directory on the host
      NEXTCLOUD_TRUSTED_CACERTS_DIR: /shared
      SKIP_DOMAIN_VALIDATION: true
    networks:
      - nextcloud-aio
      - mediaserver
    ports:
      - "87:80"
      - "8086:8080"
      - "16002:8443"
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - nextcloud_aio_mastercontainer:/mnt/docker-aio-config
      - ${DOCKERDIR}/nextcloud/config:/config      
      - ${DOCKERDIR}/nextcloud/homes:/homes
      - ${NEXTCLOUD_EXSTORAGE}:/exstorage
      - ${SHAREDDIR}:/shared
      - ${DOCKERDIR}/logs/nextcloud:/var/www/html/data/nextcloud.log
      - ${DOCKERDIR}/logs/nextcloud/supervisord:/var/log/supervisord