services:
  nzbhydra2:
    container_name: nzbhydra2.${HOST_NAME}
    hostname: nzbhydra2.${HOST_NAME}.local
    image: binhex/arch-nzbhydra2:latest
    environment:
      TZ: ${TZ}
      PUID: ${PUID}
      PGID: ${PGID}
      HOST_NAME: ${HOST_NAME}
      UMASK: 002
    networks:
      - mediaserver
    ports:
      - ${NZBHYDRA2_PORT}:5076  # Replace SERVICE_PORT with the actual port you want to expose. Add SERVICE_PORT to your .env file.
    volumes:
      # Uncomment if needed
      # - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime:ro
      - ${DOCKERDIR}/sabnzbd/watched:/data
      - ${DOCKERDIR}/nzbhydra2/config:/config
      - ${DOCKERDIR}/logs/nzbhydra2:/var/log
    restart: always
    security_opt:
      - no-new-privileges:true
    labels:      
    ## Watchtower enabled?
      - "com.centurylinklabs.watchtower.enable=true"
      ## Homepage Labels
      - "homepage.group=Media"
      - "homepage.name=NZBHydra2"
      - "homepage.icon=nzbhydra2.png"
      - "homepage.href=https://nzbhydra2.${DOMAINNAME}/"
      - "homepage.description=NZBHydra 2 is a meta search for NZB indexers"
      ## Homepage Widget currently not working until post supported
   #   - "homepage.widget.type=customapi"
   #   - "homepage.widget.url=http://nzbhydra2.${HOST_NAME}:5076/internalapi/stats?apikey=${NZBHYDRA2_API_KEY}"
   #   - "homepage.widget.key=${NZBHYDRA2_API_KEY}"
   #   - "homepage.widget.mappings[0].field=numberOfConfiguredIndexers"
   #   - "homepage.widget.mappings[0].label=Configured"
   #   - "homepage.widget.mappings[0].format=number"
   #   - "homepage.widget.mappings[1].field=numberOfEnabledIndexers"
   #   - "homepage.widget.mappings[1].label=Enabled"
   #   - "homepage.widget.mappings[1].format=number"
