services:
  nzbhydra2:
    container_name: nzbhydra2.${HOST_NAME}
    hostname: nzbhydra2.${HOST_NAME}.local
    image: binhex/arch-nzbhydra2:lastest
    environment:
      TZ: ${TZ}
      PUID: ${PUID}
      PGID: ${PGID}
      UMASK: 002
    networks:
      - mediaserver
    ports:
      - ${NZBHYDRA2_PORT}:5076  # Replace SERVICE_PORT with the actual port you want to expose. Add SERVICE_PORT to your .env file.
    volumes:
      # Uncomment if needed
      # - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime:ro
      - ${DOCKERDIR}/sabnzbd/watched:/data
      - ${DOCKERDIR}/nzbhydra2/config:/config
      - ${DOCKERDIR}/logs/nzbhydra2:/var/log
    restart: always
    security_opt:
      - no-new-privileges:true
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.nzbhydra2-rtr.entrypoints=https"
      ## Middlewares
      - "traefik.http.routers.nzbhydra2-rtr.rule=Host(nzbhydra2${HOST_SUFFIX}.${DOMAINNAME})"
      - "traefik.http.routers.nzbhydra2-rtr.middlewares=chain-oauth@file"
      ## Docker Network
      - "traefik.docker.network=mediaserver"
      ## HTTP Services
      - "traefik.http.routers.nzbhydra2-rtr.service=nzbhydra2-svc"
      - "traefik.http.services.nzbhydra2-svc.loadbalancer.server.port=5076" # Replace with the internal port of the service
      ## Watchtower enabled?
      - "com.centurylinklabs.watchtower.enable=true"
      ## Homepage Labels
      - "homepage.group=Media"
      - "homepage.name=nzbhydra2"
      - "homepage.icon=nzbhydra2.png"
      - "homepage.href=http://nzbhydra2.gillisonline.com/"
      - "homepage.description=NZBHydra 2 is a meta search for NZB indexers"
      ## Homepage Widget
      - "homepage.widget.type="
      - "homepage.widget.url=http://nzbhydra2.GillisNAS:5076/" # Replace with the internal port of the service
      - "homepage.widget.key="
