# PHP-Apache-Gillisonline - Another custom PHP application with Apache.
services:
  php-apache-gillisonline:
    container_name: php-apache-gillisonline.${HOST_NAME}
    hostname: php-apache-gillisonline.${HOST_NAME}.local
    image: php:apache
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
    networks:
      - mediaserver
    ports:
      - "${GILLISONLINE_PORT}:80"
    volumes:
      - ${DOCKERDIR}/php-apache-gillisonline/apache2:/usr/local/etc/php
      - ${DOCKERDIR}/php-apache-gillisonline/var/www/html:/var/www/html
      - ${DOCKERDIR}/logs/php-apache-gillisonline:/var/log
    restart: always
    security_opt:
      - no-new-privileges:true
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.gillisonline-rtr.entrypoints=https"
      - "traefik.http.routers.gillisonline-rtr.rule=Host(`www.${DOMAINNAME}`, `${DOMAINNAME}`)"
      - "traefik.http.routers.gillisonline-rtr.tls=true"
      ## Middlewares
      - "traefik.http.routers.gillisonline-rtr.middlewares=chain-no-auth@file"
      ## Docker Network
      - "traefik.docker.network=mediaserver"
      ## HTTP Services
      - "traefik.http.routers.gillisonline-rtr.service=gillisonline-svc"
      - "traefik.http.services.gillisonline-svc.loadbalancer.server.port=80"
      ## Watchtower enable?
      - "com.centurylinklabs.watchtower.enable=true"