# PHP-Apache-Gillisonline - Another custom PHP application with Apache.

# Note: A personal note, i had a problem with permissions as i am hosting a site for someone and using nextcloud to offer uploads
#       Host machine change ownership to sudo chown -R admin:administrators /mnt/website
#       set the files to find /mnt/website/ -type f -exec chmod 644 {} \;
#       Container set owner to chown -R root:root /var/www/html
#       Container set files to find /var/www/html/ -type f -exec chmod 644 {} \;
#       Copying the default config files before first run
#       docker run --rm -v /share/Docker/GillisDockerDepot/appdata/php-apache-gillisonline/apache2:/apache2 httpd:2.4 bash -c 'cp -r /usr/local/apache2/conf/* /apache2/'
#       docker run --rm -v /share/Docker/GillisDockerDepot/appdata/php-apache-gillisonline/apache2:/apache2 php:apache bash -c 'cp /etc/apache2/apache2.conf /apache2/'  
#       sudo chmod -R 775 /share/Docker/GillisDockerDepot/appdata/php-apache-gillisonline/var/www/html
#       sudo chown -R GilAdmin:administrators /share/Docker/GillisDockerDepot/appdata/php-apache-gillisonline/var/www/html

###HELL OF A TIME GETTING THIS RUNNING 2025####
# Step 1: Create the necessary directories for Apache configurations
# docker exec -it php-apache-gillisonline.GillisNAS mkdir -p /etc/apache2/sites-available /etc/apache2/sites-enabled

# Step 2: Create the virtual host configuration file
# docker exec -it php-apache-gillisonline.GillisNAS bash -c "cat > /etc/apache2/sites-available/000-default.conf <<- 'EOF'
# <VirtualHost *:80>
#     ServerAdmin webmaster@localhost
#     DocumentRoot /var/www/html
#
#     <Directory /var/www/html>
#         Options Indexes FollowSymLinks
#         AllowOverride All
#         Require all granted
#     </Directory>
#
#     ErrorLog \${APACHE_LOG_DIR}/error.log
#     CustomLog \${APACHE_LOG_DIR}/access.log combined
# </VirtualHost>
# EOF"

# Step 3: Enable the site by creating a symlink
# docker exec -it php-apache-gillisonline.GillisNAS ln -s /etc/apache2/sites-available/000-default.conf /etc/apache2/sites-enabled/

# Step 4: Ensure the correct modules are loaded in the Apache configuration
# docker exec -it php-apache-gillisonline.GillisNAS bash -c "echo 'LoadModule mime_module /usr/lib/apache2/modules/mod_mime.so' >> /etc/apache2/apache2.conf"

# Step 5: Create or update the .htaccess file to set MIME types and DirectoryIndex
# docker exec -it php-apache-gillisonline.GillisNAS bash -c "cat > /var/www/html/.htaccess <<- 'EOF'
# AddType text/html .html
# AddType text/css .css
# AddType application/javascript .js
# DirectoryIndex index.html
# EOF"

# Step 6: Update the virtual host configuration file to set MIME types and DirectoryIndex
# docker exec -it php-apache-gillisonline.GillisNAS bash -c "cat >> /etc/apache2/sites-available/000-default.conf <<- 'EOF'
# AddType text/html .html
# AddType text/css .css
# AddType application/javascript .js
# DirectoryIndex index.html
# ErrorDocument 404 /404.html
# EOF"

# Step 7: Restart Apache to apply the changes
# docker exec -it php-apache-gillisonline.GillisNAS apachectl restart

# Step 8: Verify the configuration with the configtest command
# docker exec -it php-apache-gillisonline.GillisNAS apachectl configtest

# Step 9: Check the Apache logs for any issues
# docker logs php-apache-gillisonline.GillisNAS

# Additional Step: Fix permissions and ownership of files (if needed)
# find /share/Docker/GillisDockerDepot/appdata/php-apache-gillisonline/var/www/html/assets/img/portfolio -type f -exec chmod 644 {} \;
# find /share/Docker/GillisDockerDepot/appdata/php-apache-gillisonline/var/www/html/assets/img/portfolio -type d -exec chmod 755 {} \;
# chown -R www-data:www-data /share/Docker/GillisDockerDepot/appdata/php-apache-gillisonline/var/www/html/assets/img/portfolio


services:
  php-apache-gillisonline:
    container_name: php-apache-gillisonline.${HOST_NAME}
    hostname: php-apache-gillisonline.${HOST_NAME}.local
    image: php:apache
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
      DOMAINNAME: ${DOMAINNAME}
      APACHE_CONFDIR: /etc/apache2
      APACHE_RUN_DIR: /var/run/apache2
      APACHE_LOCK_DIR: /var/lock/apache2
      APACHE_LOG_DIR: /var/log/apache2
      APACHE_PID_FILE: /var/run/apache2/apache2.pid
      APACHE_RUN_USER: www-data
      APACHE_RUN_GROUP: www-data
    networks:
      - mediaserver
#    ports:
#      - "${DOMAINNAME_PORT}:80"
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "7"
    volumes:
      - ${DOCKERDIR}/php-apache-gillisonline/apache2:/etc/apache2
      - ${DOCKERDIR}/php-apache-gillisonline/var/www/html:/var/www/html
      - ${DOCKERDIR}/logs/php-apache-gillisonline:/var/log/apache2
    restart: always
    entrypoint: [
      "sh", "-c", 
      "if [ ! -f /etc/apache2/apache2.conf ]; then cp -r /etc/apache2/* /etc/apache2; fi; exec apache2-foreground"
    ]
    security_opt:
      - no-new-privileges:true
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.gillisonline-rtr.entrypoints=https"
      - "traefik.http.routers.gillisonline-rtr.rule=Host(`www.${DOMAINNAME}`) || Host(`${DOMAINNAME}`)"
      - "traefik.http.routers.php-apache-gillisonline-rtr.tls.options=tls-opts@file"
      ## Middlewares
      - "traefik.http.routers.gillisonline-rtr.middlewares=chain-no-auth@file"
      ## Docker Network
      - "traefik.docker.network=mediaserver"
      ## HTTP Services
      - "traefik.http.routers.gillisonline-rtr.service=gillisonline-svc"
      - "traefik.http.services.gillisonline-svc.loadbalancer.server.port=80"
      ## Watchtower enable?
      - "com.centurylinklabs.watchtower.enable=true"
      ## Homepage Labels
      - "homepage.group=Infrastructure"
      - "homepage.name=Gillisonline"
      - "homepage.icon=https://gillisonline.com/apple-touch-icon.png"
      - "homepage.href=http://www.gillisonline.com"
      - "homepage.description=Gillisonline website"
