# PHP-Apache-Gillisonline - Another custom PHP application with Apache.
services:
  php-apache-gillisonline:
    container_name: php-apache-gillisonline.${HOST_NAME}
    hostname: php-apache-gillisonline.${HOST_NAME}.local
    image: php:apache
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
      APACHE_CONFDIR: /etc/apache2
    networks:
      - mediaserver
#    ports:
#      - "${GILLISONLINE_PORT}:80"
    volumes:
      - ${DOCKERDIR}/php-apache-gillisonline/apache2:/etc/apache2
      - ${DOCKERDIR}/php-apache-gillisonline/var/www/html:/var/www/html
      - ${DOCKERDIR}/logs/php-apache-gillisonline:/var/log/apache2
    restart: always
    entrypoint: [
      "sh", "-c", 
      "if [ ! -f /etc/apache2/apache2.conf ]; then cp -r /etc/apache2/* /etc/apache2; fi; exec apache2-foreground"
    ]
    security_opt:
      - no-new-privileges:true
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.gillisonline-rtr.entrypoints=https"
      - "traefik.http.routers.gillisonline-rtr.rule=Host(`www.${DOMAINNAME}`, `${DOMAINNAME}`)"
      - "traefik.http.routers.gillisonline-rtr.tls=true"
      ## Middlewares
      - "traefik.http.routers.gillisonline-rtr.middlewares=chain-no-auth@file"
      ## Docker Network
      - "traefik.docker.network=mediaserver"
      ## HTTP Services
      - "traefik.http.routers.gillisonline-rtr.service=gillisonline-svc"
      - "traefik.http.services.gillisonline-svc.loadbalancer.server.port=80"
      ## Watchtower enable?
      - "com.centurylinklabs.watchtower.enable=true"
