# PHP-Apache-AWL - A custom PHP application with Apache.

# Note: A personal note, i had a problem with permissions as i am hosting a site for someone and using nextcloud to offer uploads
#       Host machine change ownership to sudo chown -R admin:administrators /mnt/website
#       set the files to find /mnt/website/ -type f -exec chmod 644 {} \;
#       Container set owner to chown -R root:root /var/www/html
#       Container set files to find /var/www/html/ -type f -exec chmod 644 {} \;

services:
  php-apache-awl:
    container_name: php-apache-awl.${HOST_NAME}
    hostname: php-apache-awl.${HOST_NAME}.local
    image: php:apache
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
      APACHE_CONFDIR: /etc/apache2
    networks:
      - mediaserver
 #   ports:
 #     - "${AWL_PORT}:80"
    volumes:
      - ${DOCKERDIR}/php-apache-gillisonline/apache2:/etc/apache2
      - ${DOCKERDIR}/php-apache-awl/var/www/html:/var/www/html
      - ${DOCKERDIR}/logs/php-apache-awl:/var/log/apache2
    restart: always
    entrypoint: [
      "sh", "-c", 
      "if [ ! -f /etc/apache2/apache2.conf ]; then cp -r /etc/apache2/* /etc/apache2; fi; exec apache2-foreground"
    ]
    security_opt:
      - no-new-privileges:true
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.awl-rtr.entrypoints=https"
      - "traefik.http.routers.awl-rtr.rule=Host(`${SECONDDOMAINNAME}`)"
      - "traefik.http.routers.awl-rtr.tls=true"
      ## Middlewares
      - "traefik.http.routers.awl-rtr.middlewares=chain-no-auth@file"
      ## Docker Network
      - "traefik.docker.network=mediaserver"
      ## HTTP Services
      - "traefik.http.routers.awl-rtr.service=awl-svc"
      - "traefik.http.services.awl-svc.loadbalancer.server.port=80"
      ## Watchtower enable?
      - "com.centurylinklabs.watchtower.enable=true"