# PHP-Apache-Gillisonline - Another custom PHP application with Apache.

# Note: A personal note, i had a problem with permissions as i am hosting a site for someone and using nextcloud to offer uploads
#       Host machine change ownership to sudo chown -R admin:administrators /mnt/website
#       set the files to find /mnt/website/ -type f -exec chmod 644 {} \;
#       Container set owner to chown -R root:root /var/www/html
#       Container set files to find /var/www/html/ -type f -exec chmod 644 {} \;

services:
  php-apache-gillisonline:
    container_name: php-apache-gillisonline.${HOST_NAME}
    hostname: php-apache-gillisonline.${HOST_NAME}.local
    image: php:apache
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
      DOMAINNAME: ${DOMAINNAME}
      APACHE_CONFDIR: /etc/apache2
    networks:
      - mediaserver
#    ports:
#      - "${DOMAINNAME_PORT}:80"
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "7"
    volumes:
      - ${DOCKERDIR}/php-apache-gillisonline/apache2:/etc/apache2
      - ${DOCKERDIR}/php-apache-gillisonline/var/www/html:/var/www/html
      - ${DOCKERDIR}/logs/php-apache-gillisonline:/var/log/apache2
    restart: always
    entrypoint: [
      "sh", "-c", 
      "if [ ! -f /etc/apache2/apache2.conf ]; then cp -r /etc/apache2/* /etc/apache2; fi; exec apache2-foreground"
    ]
    security_opt:
      - no-new-privileges:true
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.gillisonline-rtr.entrypoints=https"
      - "traefik.http.routers.gillisonline-rtr.rule=Host(`www.${DOMAINNAME}`) || Host(`${DOMAINNAME}`)"
      - "traefik.http.routers.gillisonline-rtr.tls=true"
      ## Middlewares
      - "traefik.http.routers.gillisonline-rtr.middlewares=chain-no-auth@file"
      ## Docker Network
      - "traefik.docker.network=mediaserver"
      ## HTTP Services
      - "traefik.http.routers.gillisonline-rtr.service=gillisonline-svc"
      - "traefik.http.services.gillisonline-svc.loadbalancer.server.port=80"
      ## Watchtower enable?
      - "com.centurylinklabs.watchtower.enable=true"
