# PHP-Apache-AWL - A custom PHP application with Apache.

# Note: A personal note, i had a problem with permissions as i am hosting a site for someone and using nextcloud to offer uploads
#       Host machine change ownership to sudo chown -R admin:administrators /mnt/website
#       set the files to find /mnt/website/ -type f -exec chmod 644 {} \;
#       Container set owner to chown -R root:root /var/www/html
#       Container set files to find /var/www/html/ -type f -exec chmod 644 {} \;
#       Copying the default config files before first run
#       docker run --rm -v /share/Docker/GillisDockerDepot/appdata/php-apache/apache2:/apache2 httpd:2.4 bash -c 'cp -r /usr/local/apache2/conf/* /apache2/'
#       sudo chmod -R 775 /share/Docker/GillisDockerDepot/appdata/php-apache-awl/var/www/html
#       sudo chown -R GilAdmin:everyone /share/Docker/GillisDockerDepot/appdata/php-apache-awl/var/www/html
#       docker exec -it nextcloud-aio-nextcloud bash -c 'chown -R www-data:www-data /share/Docker/GillisDockerDepot/appdata/php-apache-awl/var/www/html; chmod -R 775 /share/Docker/GillisDockerDepot/appdata/php-apache-awl/var/www/html; echo "Set permissions for website directory in /share/Docker/GillisDockerDepot/appdata/php-apache-awl/var/www/html"'

services:
  php-apache-awl:
    container_name: php-apache-awl.${HOST_NAME}
    hostname: php-apache-awl.${HOST_NAME}.local
    image: php:apache
    environment:
      TZ: ${TZ}
      PUID: ${PUID}
      PGID: ${PGID}
      SECONDDOMAINNAME: ${SECONDDOMAINNAME}
      APACHE_CONFDIR: /etc/apache2
    networks:
      - mediaserver
 #   ports:
 #     - "${DOMAINNAME2_PORT}:80"
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "7"
    volumes:
      - ${DOCKERDIR}/php-apache-gillisonline/apache2:/etc/apache2
      - ${DOCKERDIR}/php-apache-awl/var/www/html:/var/www/html
      - ${DOCKERDIR}/logs/php-apache-awl:/var/log/apache2
    restart: always
    entrypoint: [
      "sh", "-c", 
      "if [ ! -f /etc/apache2/apache2.conf ]; then cp -r /etc/apache2/* /etc/apache2; fi; exec apache2-foreground"
    ]
    security_opt:
      - no-new-privileges:true
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.awl-rtr.entrypoints=https"
      - "traefik.http.routers.awl-rtr.rule=Host(`${SECONDDOMAINNAME}`)"
      - "traefik.http.routers.awl-rtr.tls=true"
      ## Middlewares
      - "traefik.http.routers.awl-rtr.middlewares=chain-no-auth@file"
      ## Docker Network
      - "traefik.docker.network=mediaserver"
      ## HTTP Services
      - "traefik.http.routers.awl-rtr.service=awl-svc"
      - "traefik.http.services.awl-svc.loadbalancer.server.port=80"
      ## Watchtower enable?
      - "com.centurylinklabs.watchtower.enable=true"