# Picard - A cross-platform music tagger.
services:
  picard:
    container_name: picard.${HOST_NAME}
    hostname: picard.${HOST_NAME}.local
    image: mikenye/picard:latest
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
      DOMAINNAME: ${DOMAINNAME}
      DISPLAY_HEIGHT: 1080
      DISPLAY_WIDTH: 1920
    networks:
      - mediaserver
    ports:
      - "${PICARD_PORT}:5800"
    volumes:
      - ${DOCKERDIR}/picard/config:/config:rw
      - ${MEDIASHARE}/Music:/Music:rw
      - ${MEDIASHARE}/Videos/MusicVideos:/MusicVideos:rw
      - ${DOCKERDIR}/logs/picard:/var/log
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    labels:
      ## Watchtower enable?
      - "com.centurylinklabs.watchtower.enable=true"
      ## Homepage Labels
      - "homepage.group=Media"
      - "homepage.name=Picard"
      - "homepage.icon=music"
      - "homepage.href=https://picard.${DOMAINNAME}/"
      - "homepage.description=MusicBrainz tagger and metadata editor"
