# Pi-hole - A network-wide ad blocker.

# Notes:
# This may need to change if you are running on windows or linux. Hence the commented variables etc
# Windows: Suggested, new-NetFirewallRule -DisplayName "Docker Desktop Backend" -Direction Inbound -Program "C:\program files\docker\docker\resources\com.docker.backend.exe" -Action Allow -Profile Private,Public
#

services:
  pihole:
    container_name: pihole.${HOST_NAME}
    hostname: pihole.${HOST_NAME}.local
    image: pihole/pihole:latest 
    cap_add:
         # Required if you are using Pi-hole as your DHCP server, else not needed    
      - NET_ADMIN
      - SYS_TIME
      - SYS_NICE
    environment:
      TZ: ${TZ}      
      HOSTNAME: pihole.${HOST_NAME}
      #WEBPASSWORD_FILE: /run/secrets/pihole_password
      FTLCONF_webserver_api_password: ${PIHOLE_WEBPASSWORD}
      FTLCONF_dns_upstreams: 1.1.1.1;1.0.0.1
      FTLCONF_dns_revServers: true,192.168.2.0/24,192.168.2.1#53,local
      FTLCONF_debug_api: true
      TAIL_FTL_LOG: '1' # or '0' to disable
      DHCP_ACTIVE: true
      DHCP_START: 192.168.2.50
      DHCP_END: 192.168.2.255
      DHCP_ROUTER: 192.168.2.1
      TEMPERATUREUNIT: c
    networks:
      pihole_network:
        ipv4_address: ${PIHOLE_IP}  
    volumes:
      - ${DOCKERDIR}/pihole/etc:/etc/pihole
      - ${DOCKERDIR}/pihole/dnsmasq.d:/etc/dnsmasq.d
      - ${DOCKERDIR}/logs/pihole:/var/log
      - ${DOCKERDIR}/logs/pihole/lighttpd:/var/log/lighttpd
    restart: always
    secrets:
      - pihole_password
    labels:
      - "com.centurylinklabs.watchtower.enable=true"