# Plex - A media server to organize and stream your media.
# Note: Some stuff has to be set manually
#       Settings, Remote Access, Intenet upload speeds: set to your speed
#       Settings, Library, Select: Scan my library Auto, Run a Partial, Scan my library perd, 
#         Video played threshold 95%
#       Settings, Network, LAN Networks: 127.0.0.1/32,10.0.27.0/24,172.29.0.0/16,192.168.2.0/24, uncheck enable Relay, 
#         Custom server access URLs: https://plex.YOURNAME.gillisonline.com:443,https://YOURIP:32400
#         List of IP addresses and networks that are allowed without auth: 127.0.0.1/32,10.0.27.0/24,172.29.0.0/16,192.168.2.0/24
#       Settings, Transcode, Transcoder temporary directory: /transcode
#         If you paid for plex pass ensure these are selected Use hardware-accelerated video encoding, Use hardware acceleration when available
#       Settings, Extras, Include Cinema Trailers from new and upcoming movies in theaters
#       to restore playlists from old plex server https://soundiiz.com/webapp/playlists/spotify
# 
#       Get Token:  sudo grep 'PlexOnlineToken=' appdata/plex/config/Plex\ Media\ Server/Preferences.xml | sed 's/.*PlexOnlineToken="\([^"]*\)".*/\1/'
#

services:
  plextest:
    container_name: plextest.${HOST_NAME}
    hostname: plextest.${HOST_NAME}.local
    image: plexinc/pms-docker:plexpass
    devices:
      - /dev/dri:/dev/dri
    environment:
      TZ: ${TZ}
      PUID: 0
      PGID: 0
      DOMAINNAME: ${DOMAINNAME}
      UMASK: 002
      ADVERTISE_IP: "https://plextest.${HOST_NAME}.${DOMAINNAME}:443,https://${SERVER_IP}:32400"
      ALLOWED_NETWORKS: ${LOCAL_NETWORK} # Add manual, Settings, Network, LAN Networks
      HOSTNAME: plextest.${HOST_NAME}
      #PLEX_CLAIM_FILE: /run/secrets/plextest_claim # Claim _file does not seem to be working with binhex version
      PLEX_CLAIM: "claim-96XgTe_fsjF3m1rg12xp"
      PLEX_SERVER_NAME: plextest.${HOST_NAME}
      VERSION: docker
      TRANS_DIR: /transcode # offload transcoding to memory
    networks:
      - mediaserver
    dns:
      - 8.8.8.8  # Google DNS
      - 1.1.1.1  # Cloudflare DNS
    ports:
      - "32401:32400/tcp"
      - "1902:1900/udp"
      - "32415:32410/udp"
      - "32416:32412/udp"
      - "32417:32413/udp"
      - "32418:32414/udp"
      - "32470:32469/tcp"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DOCKERDIR}/plextest/config:/config
      - ${MEDIASHARE}:/media
      - /dev/shm/plextest:/transcode # offload transcoding to memory
      - ${DOCKERDIR}/logs/plextest:/var/log
    restart: unless-stopped
    secrets:
      - plextest_claim
    security_opt:
      - no-new-privileges:true
    labels:
      ## Watchtower Enable
      - "com.centurylinklabs.watchtower.enable=true"
