# Plex - A media server to organize and stream your media.
# Note: Some stuff has to be set manually
#       Settings, Remote Access, Intenet upload speeds: set to your speed
#       Settings, Library, Select: Scan my library Auto, Run a Partial, Scan my library perd, 
#         Video played threshold 95%
#       Settings, Network, LAN Networks: 127.0.0.1/32,10.0.27.0/24,172.29.0.0/16,192.168.2.0/24, uncheck enable Relay, 
#         Custom server access URLs: https://plex.YOURNAME.gillisonline.com:443,https://YOURIP:32400
#         List of IP addresses and networks that are allowed without auth: 127.0.0.1/32,10.0.27.0/24,172.29.0.0/16,192.168.2.0/24
#       Settings, Transcode, Transcoder temporary directory: /transcode
#         If you paid for plex pass ensure these are selected Use hardware-accelerated video encoding, Use hardware acceleration when available
#       Settings, Extras, Include Cinema Trailers from new and upcoming movies in theaters
#       to restore playlists from old plex server https://soundiiz.com/webapp/playlists/spotify
# 
#       Get Token:  sudo grep 'PlexOnlineToken=' appdata/plex/config/Plex\ Media\ Server/Preferences.xml | sed 's/.*PlexOnlineToken="\([^"]*\)".*/\1/'
#

services:
  plex:
    container_name: plex.${HOST_NAME}
    hostname: plex.${HOST_NAME}.local
    image: binhex/arch-plexpass:latest
    devices:
      - /dev/dri:/dev/dri
    environment:
      TZ: ${TZ}
      PUID: 0
      PGID: 0
      DOMAINNAME: ${DOMAINNAME}
      UMASK: 002
      ADVERTISE_IP: "https://plex.${HOST_NAME}.${DOMAINNAME}:443,https://${SERVER_IP}:32400"
      ALLOWED_NETWORKS: ${LOCAL_NETWORK} # Add manual, Settings, Network, LAN Networks
      HOSTNAME: plex.${HOST_NAME}
      PLEX_CLAIM_FILE: /run/secrets/plex_claim # input claim number into file after first run
      PLEX_SERVER_NAME: plex.${HOST_NAME}
      TV_SHOWS_PATH: /media/Videos/TV 
      MOVIES_PATH: /media/Videos/Movies 
      MUSIC_PATH: /media/Music 
      PHOTOS_PATH: /media/Photos
      ANIMATED_TV_PATH: /media/Videos/KidsTV
      ANIMATED_MOVIES_PATH: /media/Videos/KidsMovies
      VERSION: docker
      TRANS_DIR: /transcode # offload transcoding to memory
    networks:
      - mediaserver
    ports:
      - "${PLEX_PORT}:32400/tcp"
      - "3005:3005/tcp"
      - "8324:8324/tcp"
      - "32469:32469/tcp"
      - "1901:1900/udp"
      - "32410:32410/udp"
      - "32412:32412/udp"
      - "32413:32413/udp"
      - "32414:32414/udp"
      - "33400:33400"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DOCKERDIR}/plex/config:/config
      - ${MEDIASHARE}:/media
      - /dev/shm/plex:/transcode # offload transcoding to memory
      - ${DOCKERDIR}/logs/plex:/var/log
    restart: always
    secrets:
      - plex_claim
    security_opt:
      - no-new-privileges:true
    labels:
      ## Watchtower Enable
      - "com.centurylinklabs.watchtower.enable=true"
      ## Homepage Labels
      - "homepage.group=Media"
      - "homepage.name=Plex"
      - "homepage.icon=plex.png"
      - "homepage.href=https://plex.${DOMAINNAME}/"
      - "homepage.description=Stream your favorite media"
      ## Homepage Widget
      - "homepage.widget.type=plex"
      - "homepage.widget.url=http://plex.${HOST_NAME}:32400"
      - "homepage.widget.key=${PLEX_TOKEN}"

