# Prowlarr - A multi-indexer management tool.
services:
  prowlarr:
    container_name: prowlarr.${HOST_NAME}
    hostname: prowlarr.${HOST_NAME}.local
    image: ghcr.io/linuxserver/prowlarr:latest
    environment:
      TZ: ${TZ}
      PGID: ${PGID}
      PUID: ${PUID}
      DOMAINNAME: ${DOMAINNAME}
    networks:
      - mediaserver
    ports:
      - "${PROWLARR_PORT}:9696"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DOCKERDIR}/prowlarr/config:/config
      - ${USERDOWNLOAD}/Torrents:/downloads
      - ${DOCKERDIR}/logs/prowlarr:/var/log
    restart: always
    security_opt:
      - no-new-privileges:true
    labels:
      ## Watchtower Enable
      - "com.centurylinklabs.watchtower.enable=true"
      ## Homepage Labels
      - "homepage.group=Media"
      - "homepage.name=Prowlarr"
      - "homepage.icon=prowlarr.png"
      - "homepage.href=https://prowlarr.${DOMAINNAME}/"
      - "homepage.description=Indexer manager"
      ## Homepage Widget
      - "homepage.widget.type=prowlarr"
      - "homepage.widget.url=http://prowlarr.${HOST_NAME}:9696"
      - "homepage.widget.key=${PROWLARR_API_KEY}"
