# Radarr - Automatic movie download and management tool.
services:
  radarr:
    container_name: radarr.${HOST_NAME}
    hostname: radarr.${HOST_NAME}.local
    image: linuxserver/radarr:latest
    environment:
      TZ: ${TZ}
      PGID: ${PGID}
      PUID: ${PUID}
      DOMAINNAME: ${DOMAINNAME}
    networks:
      - mediaserver
    ports:
      - "${RADARR_PORT}:7878"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DOCKERDIR}/radarr/config:/config
      - ${USERDOWNLOAD}/Torrents:/downloads
      - ${MEDIASHARE}:/media
      - ${DOCKERDIR}/logs/radarr:/var/log
    restart: always
    security_opt:
      - no-new-privileges:true
    labels:
      ## Watchtower Enable
      - "com.centurylinklabs.watchtower.enable=true"
      ## Homepage Labels
      - "homepage.group=Media"
      - "homepage.name=Radarr"
      - "homepage.icon=radarr.png"
      - "homepage.href=https://radarr.${DOMAINNAME}/"
      - "homepage.description=Movie download manager"
      ## Homepage Widget
      - "homepage.widget.type=radarr"
      - "homepage.widget.url=http://radarr.${HOST_NAME}:7878"
      - "homepage.widget.key=${RADARR_API_KEY}"
