# Readarr - An ebook and audiobook collection manager.
services:
  readarr:
    container_name: readarr.${HOST_NAME}
    hostname: readarr.${HOST_NAME}.local
    image: linuxserver/readarr:develop # In development so no latest
    environment:
      TZ: ${TZ}
      PGID: ${PGID}
      PUID: ${PUID}
      DOMAINNAME: ${DOMAINNAME}
      UMASK: 2
    networks:
      - mediaserver
    ports:
      - "${READARR_PORT}:8787"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DOCKERDIR}/readarr/config:/config
      - ${MEDIASHARE}/Books:/books
      - ${USERDOWNLOAD}/Torrents:/downloads
      - ${DOCKERDIR}/logs/readarr:/var/log
    restart: always
    security_opt:
      - no-new-privileges:true
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.readarr-rtr.entrypoints=https"
      - "traefik.http.routers.readarr-rtr.rule=Host(`readarr.${DOMAINNAME}`)"
      - "traefik.http.routers.readarr-rtr.middlewares=chain-oauth@file"
      - "traefik.http.routers.readarr-rtr.tls.options=tls-opts@file"
      ## Docker Network
      - "traefik.docker.network=mediaserver"
      ## HTTP Services
      - "traefik.http.routers.readarr-rtr.service=readarr-svc"
      - "traefik.http.services.readarr-svc.loadbalancer.server.port=8787"
      ## Watchtower Enable
      - "com.centurylinklabs.watchtower.enable=true"
      ## Homepage Labels
      - "homepage.group=Media"
      - "homepage.name=Readarr"
      - "homepage.icon=readarr.png"
      - "homepage.href=http://readarr.gillisonline.com/"
      - "homepage.description=Book download manager"
      ## Homepage Widget
      - "homepage.widget.type=readarr"
      - "homepage.widget.url=http://readarr.gillisonline.com:8787"
      - "homepage.widget.key=${READARR_API_KEY}"

