# SABnzbd - An open-source binary newsreader.
services:
  sabnzbd:
    container_name: sabnzbd.${HOST_NAME}
    hostname: sabnzbd.${HOST_NAME}.lan
    image: lscr.io/linuxserver/sabnzbd:latest
    environment:
      TZ: ${TZ}
      PGID: ${PGID}
      PUID: ${PUID}
      DOMAINNAME: ${DOMAINNAME}
      SABNZBD_HOSTS: localhost,127.0.0.1,::1,sabnzbd.${DOMAINNAME},sabnzbd.${HOST_NAME}
    networks:
      - mediaserver
    ports:
      - "${SABNZBD_PORT}:8080"
    volumes:
      - ${DOCKERDIR}/sabnzbd/config:/config
      - ${USERDOWNLOAD}/Torrents:/downloads
      - ${DOCKERDIR}/logs/sabnzbd:/var/log
    restart: always
    security_opt:
      - no-new-privileges:true
    labels:
      ## Watchtower Enable
      - "com.centurylinklabs.watchtower.enable=true"
      ## Homepage Labels
      - "homepage.group=Media"
      - "homepage.name=Sabnzbd"
      - "homepage.icon=sabnzbd.png"
      - "homepage.href=https://sabnzbd.${DOMAINNAME}/"
      - "homepage.description=NZB downloader"
      ## Homepage Widget
      - "homepage.widget.type=sabnzbd"
      - "homepage.widget.url=http://sabnzbd.${HOST_NAME}:8080"      
      - "homepage.widget.key=${SABNZDB_API_KEY}"