# Tdarr Node - A node instance for the Tdarr tool.
services:
  tdarr_node:
    container_name: tdarr_node.${HOST_NAME}
    hostname: tdarr_node.${HOST_NAME}.lan
    image: haveagitgat/tdarr_node:2.45.01
    environment:
      TZ: ${TZ}
      PGID: ${PGID}
      PUID: ${PUID}
      UMASK_SET: 002
      nodeName: tdarr_node.${HOST_NAME}
      serverIP: ${TDARR_SERVERIP}
      serverPort: ${TDARR_SERVER_PORT}
      inContainer: true # Tell tdarr its running in docker      
      serverURL: http://tdarr.${HOST_NAME}:8266
      # NVIDIA_DRIVER_CAPABILITIES: all
      # NVIDIA_VISIBLE_DEVICES: all
    networks:
      - mediaserver
    ports:
      - "${TDARR_NODE_PORT}:8267"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DOCKERDIR}/tdarr/app/configs:/app/configs
      - /dev/shm/tdarr:/temp # offload transcoding to memory
      - ${MEDIASHARE}:/media
      - ${DOCKERDIR}/logs/tdarr_node:/app/logs
    # Hardware transcoding
    devices:
      - /dev/dri:/dev/dri
#    deploy:
#      resources:
#        reservations:
#          devices:
    #      - driver: nvidia # Pick one
#          - driver: vaapi # Pick one
    #      - driver: qsv # Pick one
#            count: all
#            capabilities: [gpu] 
    restart: always
    security_opt:
      - no-new-privileges:true
    labels:
      ## Watchtower Enable
      - "com.centurylinklabs.watchtower.enable=false"
