# Wizarr - A centralized media server management tool.
services:
  wizarr:
    container_name: wizarr.${HOST_NAME}
    hostname: wizarr.${HOST_NAME}.local
    image: ghcr.io/wizarrrr/wizarr:latest
    environment:
      TZ: ${TZ}
      PGID: ${PGID}
      PUID: ${PUID}
      DOMAIN: ${DOMAINNAME}
    networks:
      - mediaserver
    ports:
      - "${WIZARR_PORT}:5690"
    volumes:
      - ${DOCKERDIR}/wizarr/config:/config
      - ${DOCKERDIR}/wizarr/data/database:/data/database
      - ${DOCKERDIR}/logs/wizarr:/var/log
      - ${DOCKERDIR}/logs/wizarr/nginx:/var/log/nginx
    restart: always
    security_opt:
      - no-new-privileges:true
    labels:
      ## Watchtower Enable
      - "com.centurylinklabs.watchtower.enable=true"
      ## Homepage Labels
      - "homepage.group=Media"
      - "homepage.name=Wizarr"
      - "homepage.icon=wizarr.png"
      - "homepage.href=https://wizarr.${DOMAINNAME}/"
      - "homepage.description=Invite manager for Plex, Jellyfin, and Emby"
