# OAuth - Authorization and authentication protocol services.

# Notes:
# SECRET: Generate a random secret with openssl rand -base64 32
services:
  oauth:
    container_name: oauth.${HOST_NAME}
    hostname: oauth.${HOST_NAME}.local
    image: thomseddon/traefik-forward-auth:latest
    environment:
      DOMAINNAME: ${DOMAINNAME}
      AUTH_HOST: oauth.${DOMAINNAME}      
      CONFIG: /config
      COOKIE_DOMAIN: ${DOMAINNAME}
      DEFAULT_ACTION: auth
      DEFAULT_PROVIDER: google
      INSECURE_COOKIE: false
      LIFETIME: 2678400 # 1 month
      #LIFETIME: 86400 # 1 day, set if you want people to re-authenticate. if people are getting not authorized, check this.
      LOG_FORMAT: json
      LOG_LEVEL: info
      URL_PATH: /_oauth
    networks:
      - mediaserver
    ports:
      - "${OAUTH_PORT}:4181"
    volumes:
  #    - ${DOCKERDIR}/oauth/config:/config
      - ${DOCKERDIR}/logs/oauth:/var/log
    restart: always
    secrets:
      - source: oauth_secrets
        target: /config
    security_opt:
      - no-new-privileges:true
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.oauth-rtr.tls=true"
      - "traefik.http.routers.oauth-rtr.entrypoints=https"
      - "traefik.http.routers.oauth-rtr.rule=Host(`oauth.${DOMAINNAME}`)"
      - "traefik.http.routers.oauth-rtr.middlewares=chain-oauth@file"
      ## Docker Network
      - "traefik.docker.network=mediaserver"
      ## HTTP Services
      - "traefik.http.routers.oauth-rtr.service=oauth-svc"
      - "traefik.http.services.oauth-svc.loadbalancer.server.port=4181"
      ## Watchtower Enable
      - "com.centurylinklabs.watchtower.enable=true"