# Cloudflare DDNS - Dynamic DNS update for Cloudflare.
services:
  cloudflare-ddns:
<<<<<<< HEAD
    container_name: cloudflare-ddns.${HOST_NAME}
    hostname: cloudflare-ddns.${HOST_NAME}.local
=======
    container_name: cloudflare-ddns.${HOST_NAME}
    hostname: cloudflare-ddns.${HOST_NAME}.local
>>>>>>> 5582466ff45c081fa05058715e176bcbef9bf4a6
    image: oznu/cloudflare-ddns:latest
    environment:
      TZ: ${TZ}
      PUID: ${PUID}
      PGID: ${PGID}
      DOMAINNAME: ${DOMAINNAME}
      API_KEY_FILE: /run/secrets/cf_token
      PROXIED: 'true'
      ZONE: ${DOMAINNAME}
    networks:
      - mediaserver
    volumes:
      - ${DOCKERDIR}/cloudflare-ddns/config:/config
      - ${DOCKERDIR}/logs/cloudflare-ddns:/var/log
    restart: always
    secrets:
      - cf_token
    security_opt:
      - no-new-privileges:true
    labels:
      ## Watchtower enabled?
      - "com.centurylinklabs.watchtower.enable=true"
