# Heimdall Internal - A separate Heimdall instance.
services:
  heimdallint:
    container_name: heimdallint.${HOST_NAME}
    hostname: heimdallint.${HOST_NAME}.local
    image: linuxserver/heimdall:latest
    environment:
      TZ: ${TZ}
      PUID: ${PUID}
      PGID: '100' #can't be an admin group.
      DOMAINNAME: ${DOMAINNAME}
    networks:
      - mediaserver
    ports:
      - "${HEIMDALLINT_PORT}:80"
    volumes:
      - ${DOCKERDIR}/heimdallint/config:/config
      - ${DOCKERDIR}/logs/heimdallint:/var/log
      - ${DOCKERDIR}/logs/heimdallint/nginx:/var/log/nginx
    restart: always
    security_opt:
      - no-new-privileges:true
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.heimdallint-rtr.entrypoints=https"
      - "traefik.http.routers.heimdallint-rtr.rule=Host(`heimdallint.${DOMAINNAME}`)"
      ## Middlewares
      - "traefik.http.routers.heimdallint-rtr.middlewares=chain-oauth@file"
      ## Docker Network      
      - "traefik.docker.network=mediaserver"
      ## HTTP Services      
      - "traefik.http.routers.heimdallint-rtr.service=heimdallint-svc"
      - "traefik.http.services.heimdallint-svc.loadbalancer.server.port=80"
      ## Watchtower enabled?
      - "com.centurylinklabs.watchtower.enable=true"
