# MotionEye - Lightweight, privacy-respecting camera management and motion detection
# Provides a web-based interface to view RTSP/MJPEG streams, configure motion zones,
# capture snapshots, and trigger automations in Home Assistant.
# Ideal for integrating multiple camera brands, enabling local alerts, and feeding AI pipelines.

services:
  motioneye:
    container_name: motioneye.${HOST_NAME}
    hostname: motioneye.${HOST_NAME}.local
    image: ccrisan/motioneye:master-amd64
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
      DOMAINNAME: ${DOMAINNAME}
      HOST_NAME: ${HOST_NAME}
    networks:
      - mediaserver
    ports:
      - "${MOTIONEYE_PORT}:8765"
    volumes:
      - ${DOCKERDIR}/motioneye/config:/etc/motioneye
      - ${DOCKERDIR}/motioneye/media:/var/lib/motioneye
      - ${DOCKERDIR}/logs/motioneye:/var/log
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - "homepage.group=Infrastructure"
      - "homepage.name=MotionEye"
      - "homepage.icon=camera.png"
      - "homepage.href=https://motioneye.${DOMAINNAME}/"
      - "homepage.description=Motion detection and camera management"