# PHP-Apache-AWL - A custom PHP application with Apache.
services:
  php-apache-awl:
    container_name: php-apache-awl.${HOST_NAME}
    hostname: php-apache-awl.${HOST_NAME}.local
    image: php:8.2.27-apache
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
    networks:
      - mediaserver
    ports:
      - "${AWL_PORT}:80"
    volumes:
      - ${DOCKERDIR}/php-apache-awl/config:/config
      - ${DOCKERDIR}/php-apache-awl/var/www/html:/var/www/html
      - ${DOCKERDIR}/logs/php-apache-awl:/var/log
    restart: always
    security_opt:
      - no-new-privileges:true
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.awl-rtr.entrypoints=https"
      - "traefik.http.routers.awl-rtr.rule=Host(`${SECONDDOMAINNAME}`)"
      - "traefik.http.routers.awl-rtr.tls=true"
      ## Middlewares
      - "traefik.http.routers.awl-rtr.middlewares=chain-no-auth@file"
      ## Docker Network
      - "traefik.docker.network=mediaserver"
      ## HTTP Services
      - "traefik.http.routers.awl-rtr.service=awl-svc"
      - "traefik.http.services.awl-svc.loadbalancer.server.port=80"
      ## Watchtower enable?
      - "com.centurylinklabs.watchtower.enable=true"