# PHP-Apache - Another custom PHP application with Apache.
services:
  php-apache:
    container_name: php-apache.${HOST_NAME}
    hostname: php-apache.${HOST_NAME}.local
    image: php:8.2.27-apache
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
    networks:
      - mediaserver
    ports:
      - "${PHP-APACHE_PORT}:80"
    volumes:
      - ${DOCKERDIR}/php-apache/apache2:/etc/apache2
      - ${DOCKERDIR}/php-apache/var/www/html:/var/www/html
      - ${DOCKERDIR}/logs/php-apache:/var/log
    restart: always
    security_opt:
      - no-new-privileges:true
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.php-apache-rtr.entrypoints=https"
      - "traefik.http.routers.php-apache-rtr.rule=Host(`www.${DOMAINNAME}`, `${DOMAINNAME}`)"
      - "traefik.http.routers.php-apache-rtr.tls=true"
      ## Middlewares
      - "traefik.http.routers.php-apache-rtr.middlewares=chain-no-auth@file"
      ## Docker Network
      - "traefik.docker.network=mediaserver"
      ## HTTP Services
      - "traefik.http.routers.php-apache-rtr.service=php-apache-svc"
      - "traefik.http.services.php-apache-svc.loadbalancer.server.port=80"
      ## Watchtower enable?
      - "com.centurylinklabs.watchtower.enable=true"