# phpMyAdmin - A web-based database management tool.
services:
  phpmyadmin:
    container_name: phpmyadmin.${HOST_NAME}
    hostname: phpmyadmin.${HOST_NAME}.local
    image: phpmyadmin/phpmyadmin:latest
    links:
      - mariadb:db
    environment:
      TZ: ${TZ}
      PUID: ${PUID}
      PGID: ${PGID}
      DOMAINNAME: ${DOMAINNAME}
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/maria_root_password
      PMA_ARBITRARY: 1
      PMA_PORT: ${DB_PORT}
    networks:
      - mediaserver
    ports:
      - "${PHPMYADMIN_PORT}:80"
    volumes:
      - ${DOCKERDIR}/phpmyadmin/config:/etc/phpmyadmin
      - ${DOCKERDIR}/logs/phpmyadmin:/var/log
    restart: always
    secrets:
      - maria_root_password
    security_opt:
      - no-new-privileges:true
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.phpmyadmin-rtr.entrypoints=https"
      - "traefik.http.routers.phpmyadmin-rtr.rule=Host(`pma.${DOMAINNAME}`)"
      - "traefik.http.routers.phpmyadmin-rtr.tls=true"
      ## Middlewares
      - "traefik.http.routers.phpmyadmin-rtr.middlewares=chain-oauth@file"
      ## Docker Network
      - "traefik.docker.network=mediaserver"
      ## HTTP Services
      - "traefik.http.routers.phpmyadmin-rtr.service=phpmyadmin-svc"
      - "traefik.http.services.phpmyadmin-svc.loadbalancer.server.port=80"
      ## Watchtower enable?
      - "com.centurylinklabs.watchtower.enable=true"

