# phpMyAdmin - A web-based database management tool.
services:
  phpmyadmin:
    container_name: phpmyadmin.${HOST_NAME}
    hostname: phpmyadmin.${HOST_NAME}.lan
    image: phpmyadmin/phpmyadmin:latest
    links:
      - mariadb:db
    environment:
      DOMAINNAME: ${DOMAINNAME}
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/maria_root_password
      PMA_ARBITRARY: 1
      PMA_PORT: ${DB_PORT}
    networks:
      - mediaserver
    ports:
      - "${PHPMYADMIN_PORT}:80"
    volumes:
      - ${DOCKERDIR}/phpmyadmin/config:/etc/phpmyadmin
      - ${DOCKERDIR}/logs/phpmyadmin:/var/log
    restart: always
    secrets:
      - maria_root_password
    security_opt:
      - no-new-privileges:true
    labels:
      ## Watchtower enable?
      - "com.centurylinklabs.watchtower.enable=true"
      ## Homepage Labels
      - "homepage.group=Infrastructure"
      - "homepage.name=phpMyAdmin"
      - "homepage.icon=database"
      - "homepage.href=https://phpmyadmin.${DOMAINNAME}/"
      - "homepage.description=Web-based MySQL/MariaDB administration"      

