# Picard - A cross-platform music tagger.
services:
  picard:
    container_name: picard.${HOST_NAME}
    hostname: picard.${HOST_NAME}.local
    image: mikenye/picard:latest
    environment:
      DISPLAY_HEIGHT: 1080
      DISPLAY_WIDTH: 1920
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
    networks:
      - mediaserver
    ports:
      - "${PICARD_PORT}:5800"
    volumes:
      - ${DOCKERDIR}/picard/config:/config:rw
      - ${MEDIASHARE}/Music:/Music:rw
      - ${MEDIASHARE}/Videos/MusicVideos:/MusicVideos:rw
      - ${DOCKERDIR}/logs/picard:/var/log
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.picard-rtr.entrypoints=https"
      - "traefik.http.routers.picard-rtr.rule=Host(`picard.${DOMAINNAME}`)"
      - "traefik.http.routers.picard-rtr.tls=true"
      ## Middlewares
      - "traefik.http.routers.picard-rtr.middlewares=chain-oauth@file"
      ## Docker Network
      - "traefik.docker.network=mediaserver"
      ## HTTP Services
      - "traefik.http.routers.picard-rtr.service=picard-svc"
      - "traefik.http.services.picard-svc.loadbalancer.server.port=5800"
      ## Watchtower enable?
      - "com.centurylinklabs.watchtower.enable=true"
