# Sonarr - Automatic TV show download and management.
services:
  sonarr:
    container_name: sonarr.${HOST_NAME}
    hostname: sonarr.${HOST_NAME}.local
    image: linuxserver/sonarr
    environment:
      TZ: ${TZ}
      PGID: ${PGID}
      PUID: ${PUID}
    networks:
      - mediaserver
    ports:
      - "${SONARR_PORT}:8989"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DOCKERDIR}/sonarr/config:/config
      - ${USERDOWNLOAD}/Torrents:/downloads
      - ${MEDIASHARE}:/media
      - ${DOCKERDIR}/logs/sonarr:/var/log
    restart: always
    security_opt:
      - no-new-privileges:true
    labels:
      - "traefik.enable=true"
      ## HTTP Routers - Bypass
      - "traefik.http.routers.sonarr-rtr-bypass.entrypoints=https"
      - "traefik.http.routers.sonarr-rtr-bypass.priority=100"
      ## HTTP Routers
      - "traefik.http.routers.sonarr-rtr.entrypoints=https"
      - "traefik.http.routers.sonarr-rtr.rule=Host(`sonarr.${DOMAINNAME}`)"
      - "traefik.http.routers.sonarr-rtr.priority=99"
      - "traefik.http.routers.sonarr-rtr.middlewares=chain-oauth@file"
      ## Docker Network
      - "traefik.docker.network=mediaserver"
      ## HTTP Services
      - "traefik.http.routers.sonarr-rtr.service=sonarr-svc"
      - "traefik.http.routers.sonarr-rtr-bypass.service=sonarr-svc"
      - "traefik.http.services.sonarr-svc.loadbalancer.server.port=8989"
      ## Watchtower Enable
      - "com.centurylinklabs.watchtower.enable=true"
