#https://login.tailscale.com/a/1699afd001794f

services:
  tailscale:
    container_name: tailscale.${HOST_NAME}
    hostname: tailscale.${HOST_NAME}.lan
    image: tailscale/tailscale:latest
    network_mode: host
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      TZ: ${TZ}
      PUID: ${PUID}
      PGID: ${PGID}
      DOMAINNAME: ${DOMAINNAME}
      TS_AUTHKEY: ${TS_AUTHKEY}
      TS_EXTRA_ARGS: --advertise-exit-node --advertise-routes=192.168.2.0/24
    #networks:
    #  - mediaserver      
    volumes:
      - /dev/net/tun:/dev/net/tun
      - ${DOCKERDIR}/tailscale/var/lib:/var/lib      
      - ${DOCKERDIR}/logs/tailscale:/var/log
    restart: always
    security_opt:
      - no-new-privileges:true    
    labels:
      ## Watchtower enabled?
      - "com.centurylinklabs.watchtower.enable=true"