# ------------------------------------------------------------------------------ 
# Unbound - Recursive DNS Resolver (IPv4 + IPv6)
# ------------------------------------------------------------------------------ 
# Provides secure, privacy-respecting DNS resolution for Pi-hole and LAN clients.
# Resolves queries from root servers, supports DNSSEC, and bypasses upstream DNS.
# IPv6-ready with static ULA address for AAAA resolution and Matter compatibility.
# ------------------------------------------------------------------------------ 

services:
  unbound:
    container_name: unbound.${HOST_NAME}
    hostname: unbound.${HOST_NAME}.lan
    image: mvance/unbound:latest
    command: ["unbound", "-d", "-c", "/opt/unbound/etc/unbound/unbound.conf"]
    cap_add:
      - NET_ADMIN
    environment:
      TZ: ${TZ}
      #PUID: ${PUID}
      #PGID: ${PGID}
      HOST_NAME: unbound.${HOST_NAME}.lan
      DOMAINNAME: ${DOMAINNAME}
    networks:
      pihole_network:
        ipv4_address: ${UNBOUND_IP}
        ipv6_address: fd00:abcd:1234::54
      ha_bridge: {}
    ports:
      - "5335:5335/udp"  # DNS over UDP
      - "5335:5335/tcp"  # DNS over TCP
    volumes:      
      - ${DOCKERDIR}/unbound/etc/unbound:/opt/unbound/etc/unbound
      - ${DOCKERDIR}/logs/unbound:/var/log/unbound
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "drill @127.0.0.1 -p 5335 cloudflare.com || exit 1"]
      interval: 30s
      timeout: 30s
      retries: 3
      start_period: 10s
    labels:
      - "com.centurylinklabs.watchtower.enable=true"