# WireGuard - A modern VPN solution.
services:
  wireguard:
    container_name: wireguard.${HOST_NAME}
    hostname: wireguard.${HOST_NAME}.local
    image: lscr.io/linuxserver/wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      TZ: ${TZ}
      PGID: ${PGID}
      PUID: ${PUID}
      ALLOWEDIPS: 0.0.0.0/0
      INTERNAL_SUBNET: 10.0.28.0
      PEERDNS: auto
      PEERS: 10
      SERVERPORT: 51820
      SERVERURL: auto      
    networks:
      - mediaserver
    ports:      
      - "${WIREGUARD_PORT}:51820/udp"
    volumes:
      - ${DOCKERDIR}/wireguard/config:/config/
      - ${DOCKERDIR}/wireguard/lib/modules:/lib/modules/
      - ${DOCKERDIR}/logs/wireguard:/var/log
    restart: always
    security_opt:
      - no-new-privileges:true
    labels:
      ## Watchtower Enable
      - "com.centurylinklabs.watchtower.enable=true"
