# Cloudflare Tunnel - Secure outbound tunnel to Cloudflare edge
services:
  cloudflared:
    container_name: cloudflared.${HOST_NAME}
    hostname: cloudflared.${HOST_NAME}.local
    image: cloudflare/cloudflared:latest
    command: tunnel run test-tunnel
    environment:
      TUNNEL_TOKEN: ${CLOUDFLARED_TUNNEL_TOKEN}  # You’ll get this after `cloudflared tunnel login`
    networks:
      - mediaserver
    volumes:
      - ${DOCKERDIR}/cloudflared:/home/nonroot/.cloudflared
      - ${DOCKERDIR}/logs/cloudflared:/var/log
    restart: always
    security_opt:
      - no-new-privileges:true
    labels:
      - "com.centurylinklabs.watchtower.enable=true"