# Pi-hole - A network-wide ad blocker.

# Notes:
# This may need to change if you are running on windows or linux. Hence the commented variables etc
# Windows: Suggested, new-NetFirewallRule -DisplayName "Docker Desktop Backend" -Direction Inbound -Program "C:\program files\docker\docker\resources\com.docker.backend.exe" -Action Allow -Profile Private,Public
#

services:
  pihole:
    container_name: pihole.${HOST_NAME}
    hostname: pihole.${HOST_NAME}.lan
    image: pihole/pihole:latest 
    cap_add:
         # Required if you are using Pi-hole as your DHCP server, else not needed    
      - NET_ADMIN
      - SYS_TIME
      - SYS_NICE
      - CAP_NET_RAW
    environment:
      TZ: ${TZ}      
      HOST_NAME: pihole.${HOST_NAME}.lan
      #WEBPASSWORD_FILE: /run/secrets/pihole_password
      FTLCONF_webserver_api_password: ${PIHOLE_WEBPASSWORD}
      #FTLCONF_dns_upstreams: 1.1.1.1;1.0.0.1
      FTLCONF_dns_upstreams: 127.0.0.1#5335;::1#5335
      FTLCONF_dns_revServers: true,192.168.2.0/24,192.168.2.1#53,local
      FTLCONF_debug_api: true
      TAIL_FTL_LOG: '1' # or '0' to disable
      FTLCONF_dhcp_active: true      
      FTLCONF_dhcp_start: 192.168.2.50
      FTLCONF_dhcp_end: 192.168.2.254
      FTLCONF_dhcp_router: 192.168.2.1
      FTLCONF_dhcp_leaseTime: 30d
      FTLCONF_dns_domain: local
      FTLCONF_dhcp_ipv6: true
      TEMPERATUREUNIT: c
 #   networks:
 #     pihole_network:
 #       ipv4_address: ${PIHOLE_IP}  
    network_mode: host
    volumes:
      - ${DOCKERDIR}/pihole/etc:/etc/pihole
      - ${DOCKERDIR}/pihole/dnsmasq.d:/etc/dnsmasq.d
      - ${DOCKERDIR}/logs/pihole:/var/log/pihole
      - ${DOCKERDIR}/logs/pihole-FTL:/var/log/pihole-FTL
    restart: always
    secrets:
      - pihole_password    
    labels:
      - "com.centurylinklabs.watchtower.enable=true"